#pragma once

#include "NexusFramework/Types/Numeric/Integer.h"
#include "NexusFramework/Types/Numeric/Decimal.h"
#include "NexusFramework/Types/Numeric/Enum.h"
#include "NexusFramework/Types/Strings/String.h"
#include "NexusFramework/Types/Strings/StringId.h"
#include "NexusFramework/Types/Strings/StringView.h"
#include "NexusFramework/Types/Strings/StringCApi.h"
#include "NexusFramework/Types/Strings/Utility.h"
#include "NexusFramework/Types/Containers/Array.h"
#include "NexusFramework/Types/Containers/List.h"
#include "NexusFramework/Types/Containers/Dequeue.h"
#include "NexusFramework/Types/Containers/Stack.h"
#include "NexusFramework/Types/Containers/Queue.h"
#include "NexusFramework/Types/Containers/Set.h"
#include "NexusFramework/Types/Containers/Dictionary.h"
#include "NexusFramework/Types/Containers/LinkedList.h"
#include "NexusFramework/Types/Containers/Tree.h"
#include "NexusFramework/Types/Containers/Graph.h"
#include "NexusFramework/Types/Containers/Collection.h"
#include "NexusFramework/Types/Containers/Buffer.h"
#include "NexusFramework/Types/Containers/Pool.h"
#include "NexusFramework/Types/Containers/Tuple.h"
#include "NexusFramework/Types/Containers/Utility.h"
#include "NexusFramework/Types/Functions/Delegate.h"
#include "NexusFramework/Types/Functions/Event.h"

#include "NexusFramework/Memory/Memory.h"
#include "NexusFramework/Memory/Allocator/Allocator.h"
#include "NexusFramework/Memory/Allocator/SystemAllocator.h"
#include "NexusFramework/Memory/Allocator/MemoryAllocator.h"
#include "NexusFramework/Memory/Allocator/BucketAllocator.h"
#include "NexusFramework/Memory/Allocator/StackAllocator.h"
#include "NexusFramework/Memory/Allocator/PoolAllocator.h"
#include "NexusFramework/Memory/Allocator/HeapAllocator.h"
#include "NexusFramework/Memory/Allocator/ContinuousAllocator.h"
#include "NexusFramework/Memory/Allocator/FixedAllocator.h"
#include "NexusFramework/Memory/Handle/Handle.h"
#include "NexusFramework/Memory/Handle/HandleBucket.h"
#include "NexusFramework/Memory/Handle/HandleManager.h"

#include "NexusFramework/Platform/Platform.h"

#include "NexusFramework/Misc/Templates.h"
#include "NexusFramework/Misc/Iterator/Iterator.h"
#include "NexusFramework/Misc/Iterator/IteratorAny.h"
#include "NexusFramework/Misc/Node/Node.h"
#include "NexusFramework/Misc/Hash/Hash.h"
#include "NexusFramework/Misc/Sort/Sort.h"
#include "NexusFramework/Misc/Color/Color.h"
#include "NexusFramework/Misc/Arguments/Arguments.h"
#include "NexusFramework/Misc/Pattern/Context.h"
#include "NexusFramework/Misc/Pattern/Registry.h"
#include "NexusFramework/Misc/Pattern/Factory.h"

#include "NexusFramework/Math/Math.h"
#include "NexusFramework/Math/Vector.h"
#include "NexusFramework/Math/Rotation.h"
#include "NexusFramework/Math/Matrix.h"
#include "NexusFramework/Math/Shape.h"

#include "NexusFramework/Time/Time.h"
#include "NexusFramework/Time/Timestamp.h"
#include "NexusFramework/Time/Timespan.h"
#include "NexusFramework/Time/Stopwatch.h"

#include "NexusFramework/IO/Path.h"
#include "NexusFramework/IO/Directory.h"
#include "NexusFramework/IO/File.h"
#include "NexusFramework/IO/Stream.h"

#include "NexusFramework/Serialization/Rbs.h"
#include "NexusFramework/Serialization/Yaml.h"
#include "NexusFramework/Serialization/Csv.h"

#include "NexusFramework/Threading/Thread.h"
#include "NexusFramework/Threading/Mutex.h"
#include "NexusFramework/Threading/ConditionVariable.h"
#include "NexusFramework/Threading/Atomic.h"
#include "NexusFramework/Threading/Fence.h"
#include "NexusFramework/Threading/ThreadPool.h"

#include "NexusFramework/Debug/Logger/Logger.h"
#include "NexusFramework/Debug/Profiler/Stats/Stats.h"
#include "NexusFramework/Debug/Profiler/Instruments/Instuments.h"
#include "NexusFramework/Debug/Profiler/Memory/MemoryTracker.h"

#include "NexusFramework/Types/Strings/Misc/Hash.h"
#include "NexusFramework/Types/Strings/Misc/Iterator.h"
#include "NexusFramework/Types/Strings/Misc/Serialization.h"
#include "NexusFramework/Types/Strings/Misc/String.h"
#include "NexusFramework/Types/Containers/Misc/Node.h"
#include "NexusFramework/Types/Containers/Misc/Iterator.h"
#include "NexusFramework/Types/Containers/Misc/Serialization.h"
#include "NexusFramework/Types/Containers/Misc/String.h"
#include "NexusFramework/Memory/Misc/Templates.h"
#include "NexusFramework/Memory/Misc/Memory.h"
#include "NexusFramework/Misc/Hash/Misc/Hash.h"
#include "NexusFramework/Misc/Color/Misc/Hash.h"
#include "NexusFramework/Misc/Color/Misc/Serialization.h"
#include "NexusFramework/Misc/Color/Misc/String.h"
#include "NexusFramework/Math/Misc/Hash.h"
#include "NexusFramework/Math/Misc/Serialization.h"
#include "NexusFramework/Math/Misc/String.h"
#include "NexusFramework/Time/Misc/Hash.h"
#include "NexusFramework/Time/Misc/Serialization.h"
#include "NexusFramework/Time/Misc/String.h"
#include "NexusFramework/Debug/Profiler/Stats/Misc/String.h"

#include "NexusFramework/Core/NexusFrameworkCommon.h"
