#pragma once

#include "NexusFramework/Types/Numbers/Integer.h"
#include "NexusFramework/Types/Numbers/Decimal.h"
#include "NexusFramework/Types/Numbers/Enum.h"
#include "NexusFramework/Types/Strings/String.h"
#include "NexusFramework/Types/Strings/StringId.h"
#include "NexusFramework/Types/Strings/StringView.h"
#include "NexusFramework/Types/Strings/StringCApi.h"
#include "NexusFramework/Types/Strings/StringFunctions.h"
#include "NexusFramework/Types/Strings/StringTemplate.h"
#include "NexusFramework/Types/Strings/StringHash.h"
#include "NexusFramework/Types/Strings/StringSerialization.h"
#include "NexusFramework/Types/Containers/Node.h"
#include "NexusFramework/Types/Containers/Iterator.h"
#include "NexusFramework/Types/Containers/Array.h"
#include "NexusFramework/Types/Containers/List.h"
#include "NexusFramework/Types/Containers/Dequeue.h"
#include "NexusFramework/Types/Containers/Stack.h"
#include "NexusFramework/Types/Containers/Queue.h"
#include "NexusFramework/Types/Containers/LinkedList.h"
#include "NexusFramework/Types/Containers/Set.h"
#include "NexusFramework/Types/Containers/Dictionary.h"
#include "NexusFramework/Types/Containers/Tree.h"
#include "NexusFramework/Types/Containers/Graph.h"
#include "NexusFramework/Types/Containers/Collection.h"
#include "NexusFramework/Types/Containers/Buffer.h"
#include "NexusFramework/Types/Containers/Pool.h"
#include "NexusFramework/Types/Containers/Tuple.h"
#include "NexusFramework/Types/Containers/ContainersUtils.h"
#include "NexusFramework/Types/Containers/Serialization.h"
#include "NexusFramework/Types/Containers/String.h"
#include "NexusFramework/Types/Functions/Delegate.h"
#include "NexusFramework/Types/Functions/Event.h"

#include "NexusFramework/Memory/Memory.h"
#include "NexusFramework/Memory/Handle/Handle.h"
#include "NexusFramework/Memory/Handle/HandleManager.h"
#include "NexusFramework/Memory/Allocator/Allocator.h"
#include "NexusFramework/Memory/Allocator/AllocatorContext.h"
#include "NexusFramework/Memory/Allocator/RawAllocator.h"
#include "NexusFramework/Memory/Allocator/MemoryAllocator.h"
#include "NexusFramework/Memory/Allocator/StackAllocator.h"
#include "NexusFramework/Memory/Allocator/HeapAllocator.h"
#include "NexusFramework/Memory/Allocator/PoolAllocator.h"

#include "NexusFramework/Misc/Templates.h"
#include "NexusFramework/Misc/Hash.h"
#include "NexusFramework/Misc/Sort.h"
#include "NexusFramework/Misc/Color.h"

#include "NexusFramework/Platform/Platform.h"

#include "NexusFramework/Math/Math.h"
#include "NexusFramework/Math/Vector.h"
#include "NexusFramework/Math/Rotation.h"
#include "NexusFramework/Math/Matrix.h"
#include "NexusFramework/Math/Shape.h"
#include "NexusFramework/Math/Hash.h"
#include "NexusFramework/Math/Serialization.h"
#include "NexusFramework/Math/String.h"

#include "NexusFramework/Time/Timestamp.h"
#include "NexusFramework/Time/Timespan.h"
#include "NexusFramework/Time/Stopwatch.h"
#include "NexusFramework/Time/Time.h"

#include "NexusFramework/IO/Path.h"
#include "NexusFramework/IO/Directory.h"
#include "NexusFramework/IO/File.h"
#include "NexusFramework/IO/Stream.h"

#include "NexusFramework/Serialization/Rbs.h"
#include "NexusFramework/Serialization/Yaml.h"
#include "NexusFramework/Serialization/Csv.h"

#include "NexusFramework/Threading/Thread.h"
#include "NexusFramework/Threading/Mutex.h"
#include "NexusFramework/Threading/ConditionVariable.h"
#include "NexusFramework/Threading/Atomic.h"
#include "NexusFramework/Threading/Fence.h"
#include "NexusFramework/Threading/ThreadPool.h"

#include "NexusFramework/Debug/Logger/Logger.h"
#include "NexusFramework/Debug/Profiler/Profiler.h"

#include "NexusFramework/Application/Arguments.h"
